---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: service-proxy
  labels:
    app.kubernetes.io/name: service-proxy
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: camel
    app.openshift.io/runtime: camel
  name: service-proxy
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: {{ .Values.serviceProxy.ports.https }}
  selector:
    app.kubernetes.io/name: service-proxy
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
