name: Build

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Build Plugin Image
        uses: docker/build-push-action@v3
        with:
          context: ./plugin
          push: true
          tags: cmiranda/camel-openshift-console-plugin:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build Service Proxy
        run: cd service-proxy && mvn package
      - name: Build Serivce Proxy Image
        uses: docker/build-push-action@v3
        with:
          context: ./service-proxy
          file: ./service-proxy/src/main/docker/Dockerfile.jvm
          push: true
          tags: cmiranda/camel-openshift-console-service-proxy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

